#!/bin/bash

serverPort=5201
clientPort=5201

# If no arguments are given, print this help
if [ -z "$*" ]; then echo "Use it with -s (--server) or -c (--client)"; fi

# Check if user wants to use client or server feature
for arg in "$@"
do
  #
  # Define server section
  #
  if [ "$arg" == "--server" ] || [ "$arg" == "-s" ]
  then
    
    # Script needs to run as root
    if [ "$EUID" -ne 0 ]
      then echo "Please run as root"
      exit 1
    fi
    
    echo "Installing iperf ..."
    apt -qq update > /dev/null 2>&1
    apt -qq install iperf3 -y > /dev/null 2>&1
    
    # Display IP (if possible)
    echo -e "\nHere's the IP of this machine: $(ip -o -4 addr show | awk -F '[ /]+' '/global/ {print $4}')\n"
   
    # User input
    read -r -p "Would you like to define the port for iperf? Needed if you have more than 1 daemon running. [y/N] " response
    if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]
    then      
    echo -e "\nOK. Let's define the port then ..."
      read -r -p "What port would you like iperf3 server to run? " serverPort
    else
      echo "OK! We'll use the default port."
    fi

    # Run the actual test
    iperf3 -s -p $serverPort
  fi

  # 
  # Define client section
  #
  if [ "$arg" == "--client" ] || [ "$arg" == "-c" ]
  then
    if [ "$EUID" -ne 0 ]
      then echo "Please run as root"
      exit 1
    fi
    
    echo "Installing iperf ..."
    apt -qq update > /dev/null 2>&1
    apt -qq install iperf3 -y > /dev/null 2>&1

    # User input
    read -r -p "What's the iperf3 server IP address? " ipClient
    read -r -p "Would you like to define where we should connect on the iperf3 server? Needed if not running in the default port or if you have more than 1 daemon running. [y/N] " response
    if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]
    then
      echo -e "\nOK. Let's define the port then ..."
      read -r -p "What port would you like to connect to? " clientPort
    else
      echo "OK! We'll use the default port."
    fi

    # Run the actual test
    iperf3 -c $ipClient -p $clientPort --parallel 10 -i 1 -t 60 -V | grep SUM
  fi
done
